version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo_topics
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  mariadb:
    image: mariadb
    container_name: mariadb_service
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
    ports:
      - "3308:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mongo-data:
  mariadb-data:

